development:
  adapter: postgresql
  database: abs_dev 
  username: rails_dev 
  password: ruby* 
  host: localhost

test:
  adapter: postgresql
  database: abs_tst 
  username: rails_dev 
  password: ruby* 
  host: localhost

production:
   adapter: postgresql
   database: abs_pro 
   username: abu 
   password: ruby* 
   host: localhost
