development:
  adapter: postgresql
  database: abu_dev
  username: abu 
  password: Aardvark31
  host: localhost

test:
  adapter: postgresql
  database: abu_test
  username: abu 
  password:  Aardvark31
  host: localhost

production:
   adapter: postgresql
   database: abu_live
   username: abu 
   password: Aardvark31
   host: localhost
